### ISSUE TITLE
Class methods disappear for non-ref's returned from setup-function

### ISSUE THREAD

**Issue by amjmhs** [vuejs/composition-api#474]
After updating vue-composition-api from 0.5.0 to 0.6.7 we have various problems at our application. I nailed it down to a simple use-case: https://codesandbox.io/s/vue-composition-api-with-disappearing-class-methods-i7cdc

So there is a class `A` with a method `printA`. At the setup-method we instantiate class A and return this instance as non-ref.
At the template, we cannot access `printA` because this method does not exists anymore.
```
[Vue warn]: Error in render: "TypeError: _vm.test.printA is not a function"
TypeError: _vm.test.printA is not a function
```

With version 0.5.0 it works as expected and does not throw any error.

**Comment by pikax** [comment]
Please update to [the latest version 1.0.0-beta.9](https://www.npmjs.com/package/@vue/composition-api)

**Comment by amjmhs** [comment]
@pikax any chance to backport this fix to 0.6.x ?

**Comment by pikax** [comment]
Personally I have no plans of doing that.

I would recommend updating to `1.0.0-beta.x`, the only major breaking change is not unwraping the nested refs from the setup, but that can be done on the userland.
