### ISSUE TITLE
Reactive type error

### ISSUE THREAD

**Issue by SeyyedKhandon** [vuejs/composition-api#432]
Consider this state which is using reactive, and `selectedItemForInlineEdit` that is an object which has some property includes `value`. 
```
//table.ts

  const state = reactive({
    lineHeightList: [] as string[],
    showMoreActions: -1,
    selectedRecordsList: [...props.preSelectedRecords],
    selectedItemForInlineEdit: {
      value: "",
      item: "",
      key: "",
      index: 0
    },
    inlineEditMode: false
  } as TableState);



//type.ts

export interface SelectedItemForInlineEdit {
  value: string;
  item: string;
  key: string;
  index: number;
}
export interface TableState {
  lineHeightList: string[];
  showMoreActions: number;
  selectedRecordsList: any[];
  selectedItemForInlineEdit: SelectedItemForInlineEdit;
  inlineEditMode: boolean;
}
```

It complains that `selectedItemForInlineEdit` type is a `string`, which is not
```
ERROR in C:/useTable.ts(108,37):
108:37 Property 'index' does not exist on type 'string'.
    106 |   const disableInlineEdit = (index: number) => {
    107 |     state.inlineEditMode = false;
  > 108 |     state.selectedItemForInlineEdit.index = index;
        |                                     ^
    109 |   };
Version: typescript 3.9.6
```

I know that if it was a `ref` value, I could use  ` Ref<T> `(based on [link](https://stackoverflow.com/questions/61052876/how-to-solve-vuejs-composition-apis-ref-type-error)  ), but what should I do for reactive?

(I'm using v0.5)

**Comment by antfu** [comment]
Any reason you can't use the latest version? Your problem is likely to be fixed already.

**Comment by SeyyedKhandon** [comment]
Thank you, I Upgraded to 0.6.7 and the errors have been fixed.

**Comment by SeyyedKhandon** [comment]
After update to 6.7, here is another error but on ref:

`    const policyForm: Ref<PolicyForm> = ref((null as unknown) as PolicyForm);
`

```
158:11 Type 'Ref<{ readonly profile: { label: string; content: { enabledGroups?: string[] | undefined; model: ProfileModelDataModel[]; }; profileSchema: { id: number; content: { instance: { specification: { ...; }; root: { ...; }; }; schema: { ...; }; }; description: string; ownershipMode: { ...; }; version: 1; profileSchemaVers...' is not assignable to type 'Ref<PolicyForm>'.
  Type '{ readonly profile: { label: string; content: { enabledGroups?: string[] | undefined; model: ProfileModelDataModel[]; }; profileSchema: { id: number; content: { instance: { specification: { ...; }; root: { ...; }; }; schema: { ...; }; }; description: string; ownershipMode: { ...; }; version: 1; profileSchemaVersion:...' is missing the following properties from type 'PolicyForm': __profile, __profileModel, __instance, __schema, and 6 more.
```

**Comment by antfu** [comment]
What's `PolicyForm`?

**Comment by SeyyedKhandon** [comment]
It's a Class

**Comment by antfu** [comment]
Vue doesn't handle the attributes starting with `_`, you should avoid that in your class if you want to pass it to the reactivity system.

**Comment by SeyyedKhandon** [comment]
I found the problem, it seems after upgrading to 0.6.7, vue has problem with typescript `private` fields, because when I changed them from private to public, the errors have fixed.
class PolicyForm {
  public __profile: Profile;
  public __profileModel: ProfileModel;
  public __instance: PolicyInstance;
  public __schema: PolicySchema;
  public __dataModel: WorkingDataModel = {};

![image](https://user-images.githubusercontent.com/59599950/86766213-76749780-c05f-11ea-8801-c54469db179f.png)

is there  any fix for having private fields?

**Comment by pikax** [comment]
@SeyyedKhandon please make sure you are running the latest version of the library before raising an issue.

You can fix your problem by:
```ts
class PolicyForm {
    private __profile: number;
    private __profileModel: string;
}

const policyForm = ref((null as unknown) as PolicyForm) as Ref<PolicyForm>;
```

**Comment by SeyyedKhandon** [comment]
@pikax, Thank you for your answer, its intersting that i changed the 

`const policyForm: Ref<PolicyForm> = ref((null as unknown) as PolicyForm);`

to

`const policyForm = ref((null as unknown) as PolicyForm) as Ref<PolicyForm>;`

the error has gone, what is happening? why has this occurred?(I'm asking to get the reason behind it to prevent further errors.)

**Comment by pikax** [comment]
A more clean way is:
```ts
const policyForm = ref(null) as Ref<PolicyForm | null>;
```

This happens because `vue` needs to **unwrap** all the nested refs in the object (removing `.value` from nested), for that to work with type script we wrap in a type `UnwrapRef`, making the final result be of type `Ref<UnwrapRef<T>>` and that type is different than `Ref<T>`.

When `vue` unwraps your type/class it will change it to a very similar but different type, in +90% of the usages this works perfectly but for certain use cases it doesn't, for those cases is recommended to override the types with `as Ref<T>`.

On your example you're actually overriding to a wrong type: `Ref<PolicyForm> = ref((null as unknown) as PolicyForm);` this type should be `Ref<PolicyForm | null>` but you are ignoring the typescript error saying the `null` cannot be used as `PolicyForm` and overriding the typescript types to pass `null` as `PolicyForm`, which is incorrect and will lead to unexpected behaviour.

Remember when a `ref` can be `null` or `undefined` you need to check if that ref has value: 

```ts
const policyForm = ref<PolicyForm | null>(null); // NOTE this won't be Ref<PolicyForm  | null> 

if(policyForm.value) {
 policyForm.value.execute(42)
}
```
