### ISSUE TITLE
invalid typing for optional props

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vuejs/composition-api#373]
## v0.6.2

```vue
<script lang="ts">
import { defineComponent, PropType } from '@vue/composition-api';

export default defineComponent({
  props: {
    a: Object as PropType<{ foo: number }>,
    b: {
      type: Object as PropType<{ foo: number }>,
      required: true,
    },
  },

  setup (props) {
    Math.floor(props.a!.foo);
    Math.floor(props.b.foo);
  },
});
</script>
```

For options prop (a) I'm getting the error
```
TS2339: Property 'foo' does not exist on type 'Function | { foo: number; }'.   Property 'foo' does not exist on type 'Function'.
```

Required prop is typed properly

![image](https://user-images.githubusercontent.com/15625235/84453918-6385c780-ac59-11ea-9e1e-54837e526fe8.png)

Works fine in 0.6.1

**Comment by jacekkarczmarczyk** [comment]
Looks like https://github.com/vuejs/composition-api/pull/371 is going to fix this, leaving issue open anyway in case someone else will search github for the same problem

**Comment by antfu** [comment]
Merged and release in v0.6.3. Thanks!
